# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2023-05-03T15:15:47+00:00

# manually edited

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional, Union

from pydantic import BaseModel


class PublicRelationshipSearchInput(BaseModel):
    name: str
    domains: list[str]


class ContextType(BaseModel):
    name: Optional[str] = None


class DataType(BaseModel):
    name: Optional[str] = None


class RelationshipCreateUpdateInput(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    homepage: Optional[str] = None
    description: Optional[str] = None
    contextTypes: Optional[List[ContextType]] = None
    dataTypes: Optional[List[DataType]] = None
    businessOwnerEmail: Optional[str] = None
    tags: Optional[List[str]] = None


class Status(Enum):
    NOT_ASSESSED = 'NOT_ASSESSED'
    STARTED = 'STARTED'
    REVIEW_STARTED = 'REVIEW_STARTED'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'
    COLLECTING_INFORMATION = 'COLLECTING_INFORMATION'


class AssessmentStatusHistory(BaseModel):
    date: Optional[datetime] = None
    status: Optional[Status] = None


class PrimaryContact(BaseModel):
    firstName: Optional[str] = None
    lastName: Optional[str] = None
    email: Optional[str] = None


class Status2(Enum):
    DELETED = 'DELETED'
    NOT_ONBOARDED = 'NOT_ONBOARDED'
    ONBOARDED = 'ONBOARDED'


class RecertificationType(Enum):
    MANUAL = 'MANUAL'
    AUTOMATIC = 'AUTOMATIC'
    NONE = 'NONE'


class ResidualRisk(Enum):
    NO_ACCESS = 'NO_ACCESS'
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'
    EXTREME = 'EXTREME'


class PotentialRisk(Enum):
    NO_ACCESS = 'NO_ACCESS'
    LOW = 'LOW'
    MEDIUM = 'MEDIUM'
    HIGH = 'HIGH'
    EXTREME = 'EXTREME'


class VisoUser(BaseModel):
    firstName: Optional[str] = None
    lastName: Optional[str] = None
    email: Optional[str] = None


class TagsCreateInput(BaseModel):
    tags: List[str]


class Assessment(BaseModel):
    status: Optional[Status] = None
    statusHistories: Optional[List[AssessmentStatusHistory]] = None
    completedDate: Optional[datetime] = None
    updatedDate: Optional[datetime] = None
    phaseDate: Optional[datetime] = None
    assessmentType: Optional[str] = None
    expirationDate: Optional[datetime] = None
    sentToEmail: Optional[str] = None
    createdDate: Optional[datetime] = None
    sentToFirstName: Optional[str] = None
    sentToLastName: Optional[str] = None
    sentBy: Optional[VisoUser] = None
    type: str


class CertificationAssessment(Assessment):
    pass


class RecertificationAssessment(Assessment):
    pass


class ArtifactUpdateAssessment(Assessment):
    pass


class Relationship(BaseModel):
    name: str
    id: Optional[int] = None
    status: Optional[Status2] = None
    tags: Optional[List[str]] = None
    primaryContact: Optional[PrimaryContact] = None
    recertificationType: Optional[RecertificationType] = None
    description: Optional[str] = None
    isTransitional: Optional[bool] = None
    assessments: Optional[
        List[
            Union[
                ArtifactUpdateAssessment,
                CertificationAssessment,
                RecertificationAssessment,
            ]
        ]
    ] = None
    updatedDate: Optional[datetime] = None
    residualRisk: Optional[ResidualRisk] = None
    subscribers: Optional[List[VisoUser]] = None
    homepage: Optional[str] = None
    dataTypes: Optional[List[DataType]] = None
    contextTypes: Optional[List[ContextType]] = None
    potentialRisk: Optional[PotentialRisk] = None
    createdDate: Optional[datetime] = None
    businessOwner: Optional[VisoUser] = None
    recertificationDate: Optional[datetime] = None
