on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  cog-check:
    runs-on: ubuntu-latest
    name: Check Conventional Commit Compliance
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # pick the pr HEAD instead of the merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Conventional commit check
        uses: cocogitto/cocogitto-action@v3
