on:
  push:
    tags:
      - 'release/*'

jobs:
  make-release:
    name:    Get Plugin Output
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./are-plugin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build image
        run:  docker build . -t vt -f Dockerfile.package
      - name: Get version number/name
        id:   version
        run:  echo "VERSION_NAME=$(echo $GITHUB_REF_NAME | awk -F/ '{print $NF}')" >> $GITHUB_ENV
      - name: Run image for output
        run:  docker run -e ASSERT_VERSION=$VERSION_NAME -v $(pwd):/output vt
      - name: Verify release notes
        run:  ./bin/check-release-notes
      - name: Get release notes
        id:   notes
        run: |
           echo "RELEASE_NOTES=$(tail -n+2 RELEASE-NOTES.md | sed '/^# /Q') | awk '$1=$1'" >> $GITHUB_ENV
      - name: Export env
        id:   export
        run:  |
          echo "VERSION_NAME=$VERSION_NAME" >> GITHUB_OUTPUT
          echo "RELEASE_NOTES=$RELEASE_NOTES" >> GITHUB_OUTPUT
      - name: Debug
        run:  pwd && find .
      - name: Upload tarball to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: are-plugin/viso-netskope.tar.gz
          tag: ${{ steps.export.outputs.VERSION_NAME }}
          body: |
            ${{ steps.export.outputs.RELEASE_NOTES }}
