on: [pull_request]

jobs:
  run-tests:
    name:    Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout/@v3
      - name: Build
        run:  docker build . -t vt -f Dockerfile.test
      - name: Run
        run:  docker run vt
